// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAAQ9d02wjo_XdNa38450bMjs-6hdaUU2A',
    appId: '1:972819093871:web:5b1191647117797cdb309a',
    messagingSenderId: '972819093871',
    projectId: 'artho-deta',
    authDomain: 'artho-deta.firebaseapp.com',
    storageBucket: 'artho-deta.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAauX88srQTgunS6QOYauW1FHgE2iEPeHs',
    appId: '1:972819093871:android:8ca230ec388d856ddb309a',
    messagingSenderId: '972819093871',
    projectId: 'artho-deta',
    storageBucket: 'artho-deta.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCKak8D1ETa3Amu8rdR7x27Piv1PShAA8k',
    appId: '1:972819093871:ios:94aa85c8bfd4209adb309a',
    messagingSenderId: '972819093871',
    projectId: 'artho-deta',
    storageBucket: 'artho-deta.firebasestorage.app',
    iosBundleId: 'com.example.arthoApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCKak8D1ETa3Amu8rdR7x27Piv1PShAA8k',
    appId: '1:972819093871:ios:94aa85c8bfd4209adb309a',
    messagingSenderId: '972819093871',
    projectId: 'artho-deta',
    storageBucket: 'artho-deta.firebasestorage.app',
    iosBundleId: 'com.example.arthoApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAAQ9d02wjo_XdNa38450bMjs-6hdaUU2A',
    appId: '1:972819093871:web:5754be571f89e188db309a',
    messagingSenderId: '972819093871',
    projectId: 'artho-deta',
    authDomain: 'artho-deta.firebaseapp.com',
    storageBucket: 'artho-deta.firebasestorage.app',
  );
}
